### ISSUE TITLE
安装启动后是空白的

### ISSUE THREAD

**Issue by GengGode** [Lanseria/media-srt#1]
![image](https://user-images.githubusercontent.com/47711102/181870688-9834e1e0-75fb-4d50-84ee-23540039681d.png)
如图正常安装的，但是打开后没有内容

**Comment by GengGode** [comment]
是否存在什么依赖？

**Comment by lanseria** [comment]
> 是否存在什么依赖？

我改用了`pnpm`去安装，没问题，你可以拉一下代码，重新试一下

**Comment by GengGode** [comment]
我用的release的安装包安装启动的

**Comment by GengGode** [comment]
代码的话，目前显示
![image](https://user-images.githubusercontent.com/47711102/181921169-abce9853-ac50-4995-aeb7-c0959f2c035b.png)
没找到解决方案

**Comment by GengGode** [comment]
换了pnpm正常启动进入界面了，but，这是正常的吗
![image](https://user-images.githubusercontent.com/47711102/181923500-05b4e5be-3b33-4489-ba32-2abb000934d6.png)

**Comment by GengGode** [comment]
哦哦，点进去就ok了，牛的
